##########
# SERVER #
##########
https_domain_name: hdzhang.xyz
https_listen_port: 443

max_body_size: 10485760

certfile: "./conf/server.crt"
keyfile: "./conf/server.key"

static_path: "/storage/static"


############
# DATABASE #
############
engine_str: "mysql+mysqlconnector://root:Plover!Password1@localhost:3306/plover"


###########
# STORAGE #
###########
upload_identify_path: "/storage/upload/identify"
upload_suggestion_path: "/storage/upload/suggestion"


#########
# WINXI #
#########
appid: "wx002b7e790dfa4a25"
mch_id: "1519730751"
pay_key: "Gao123456789aaaa987654312ggwwwww"

code2session_url: "https://api.weixin.qq.com/sns/jscode2session"
unifiedorder_url: "https://api.mch.weixin.qq.com/pay/unifiedorder"

#########
# MAP #
#########
map_url_tx: "https://apis.map.qq.com/ws/distance/v1"
map_key_tx: "GIUBZ-DWEWW-6CVRK-OLZWV-26UUH-5OBRT"


#########
# OTHER #
#########
query_num: 10


#########
# DEBUG #
#########
#debug: true
debug: false