# server config
https_domain_name: hdzhang.xyz
https_listen_port: 443

certfile: "./conf/server.crt"
keyfile: "./conf/server.key"

# 最大上传文件限制 10M
max_body_size: 10485760

# database
engine_str: "mysql+mysqlconnector://root:ploverpassword@localhost:3306/plover"

# storage
upload_path: "/storage/upload"

# winxi api
code2session_url: "https://api.weixin.qq.com/sns/jscode2session"

# other
query_num: 10

# debug
debug: true