# server config
https_domain_name: hdzhang.xyz
https_listen_port: 443

certfile: "./conf/server.crt"
keyfile: "./conf/server.key"

# database
engine_str: "mysql+mysqlconnector://root:ploverpassword@localhost:3306/plover"


# winxi api
code2session_url: "https://api.weixin.qq.com/sns/jscode2session"

# sms



# other
query_num: 10

# debug
debug: true